[run]
timeout = "5m"
modules-download-mode = "readonly"

[linters]
disable = [
	"golint",
	"depguard",
	"ireturn",
	"wastedassign",
	"unused",
	"stylecheck",
	"tparallel",
	"unparam",
	"rowserrcheck",
	"noctx",
	"sqlclosecheck",
	"structcheck",
	"gosimple",
	"nilerr",
	"interfacer",
	"bodyclose",
	"contextcheck",
	"maligned",
	"scopelint",
	"nolintlint",
	"wrapcheck",
	"exhaustivestruct",
	"varcheck",
	"ifshort",
	"nosnakecase",
	"deadcode",
	"exhaustruct",
]
enable-all = true
